version: '3.8'
services:
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: sbdb
      POSTGRES_PASSWORD: sbdbpassword
      POSTGRES_USER: sbdbuser
    ports:
      - 5432:5432
    volumes:
      - ./db/postgresql.conf:/etc/postgresql.conf
    command: ['postgres', '-c', 'config_file=/etc/postgresql.conf']
